apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-certificate-config
  namespace: {{ .Release.Namespace }}
data:
  certificate-config.json: |
    {{ .Values.certificateConfig | toJson | indent 4 }}