apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: cert-manager-kv-syncer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DRY_RUN
              value: "{{ .Values.sync.dryRun }}"
            - name: SYNC_INTERVAL
              value: "{{ .Values.sync.interval }}"
            - name: USE_NAME_MAPPING
              value: "{{ .Values.mapping.useNameMapping }}"
            - name: STRICT_NAME_MAPPING
              value: "{{ .Values.mapping.strictNameMapping }}"
            - name: DEFAULT_LOGGING_LEVEL
              value: "{{ .Values.logging.defaultLevel }}"
            - name: AZURE_LOGGING_LEVEL
              value: "{{ .Values.logging.azureLevel }}"
            - name: SEARCH_NAMESPACES
              value: "{{ .Values.search.namespaces }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: certificate-config
            mountPath: /etc/cert-manager-kv-syncer
            readOnly: true
      volumes:
      - name: certificate-config
        configMap:
          name: {{ .Release.Name }}-certificate-config