apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: aks-kv-syncer
      app.kubernetes.io/instance: aks-kv-syncer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aks-kv-syncer
        app.kubernetes.io/instance: aks-kv-syncer
    spec:
      containers:
        - name: aks-kv-syncer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}